AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/security-scan'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "features/**/*"

Metrics/ModuleLength:
  Exclude:
    - "spec/security/**/*"
